// Generated by apps/web/scripts/generate-ios-lucide-icons.ts.
// Do not edit.

extension NoemaIcon {
  enum Name: String {
    case archive
    case bell
    case bookOpen = "book-open"
    case bot
    case brain
    case briefcaseBusiness = "briefcase-business"
    case cable
    case calendarDays = "calendar-days"
    case camera
    case code2 = "code-2"
    case compass
    case cpu
    case dumbbell
    case fileText = "file-text"
    case folder
    case folderPlus = "folder-plus"
    case gamepad2 = "gamepad-2"
    case gauge
    case globe
    case graduationCap = "graduation-cap"
    case heart
    case heartPulse = "heart-pulse"
    case house
    case lightbulb
    case listTodo = "list-todo"
    case mapPin = "map-pin"
    case messageCircle = "message-circle"
    case mountain
    case music
    case notebookPen = "notebook-pen"
    case palette
    case pawPrint = "paw-print"
    case pencil
    case plane
    case plugZap = "plug-zap"
    case serverCog = "server-cog"
    case settings
    case shieldCheck = "shield-check"
    case smartphone
    case sparkles
    case target
    case undo2 = "undo-2"
    case user
    case users
    case utensils
    case walletCards = "wallet-cards"
  }
}
