import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const iconNames = [
  "archive",
  "bell",
  "book-open",
  "bot",
  "brain",
  "briefcase-business",
  "cable",
  "calendar-days",
  "camera",
  "code-2",
  "compass",
  "cpu",
  "dumbbell",
  "file-text",
  "folder",
  "folder-plus",
  "gamepad-2",
  "gauge",
  "globe",
  "graduation-cap",
  "heart",
  "heart-pulse",
  "house",
  "lightbulb",
  "list-todo",
  "map-pin",
  "message-circle",
  "mountain",
  "music",
  "notebook-pen",
  "palette",
  "paw-print",
  "pencil",
  "plane",
  "plug-zap",
  "server-cog",
  "settings",
  "shield-check",
  "smartphone",
  "sparkles",
  "target",
  "undo-2",
  "user",
  "users",
  "utensils",
  "wallet-cards",
] as const;

const webDirectory = resolve(import.meta.dir, "..");
const repositoryDirectory = resolve(webDirectory, "../..");
const sourceDirectory = resolve(webDirectory, "node_modules/lucide-static");
const assetDirectory = resolve(
  repositoryDirectory,
  "apps/ios/Noema/Assets.xcassets/Lucide",
);
const generatedSwiftPath = resolve(
  repositoryDirectory,
  "apps/ios/Noema/Core/Design/NoemaIcon+Generated.swift",
);
const licensePath = resolve(
  repositoryDirectory,
  "apps/ios/Noema/Licenses/Lucide.txt",
);

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const swiftCaseName = (name: string) =>
  name.replace(/-([a-z0-9])/g, (_, character: string) =>
    character.toUpperCase(),
  );

await rm(assetDirectory, { recursive: true, force: true });
await mkdir(assetDirectory, { recursive: true });
await writeFile(
  resolve(assetDirectory, "Contents.json"),
  json({ info: { author: "xcode", version: 1 } }),
);

for (const iconName of iconNames) {
  const sourcePath = resolve(sourceDirectory, "icons", `${iconName}.svg`);
  const imageSetDirectory = resolve(
    assetDirectory,
    `lucide-${iconName}.imageset`,
  );
  const outputFilename = `lucide-${iconName}.svg`;
  const svg = (await readFile(sourcePath, "utf8")).replaceAll(
    "currentColor",
    "#000000",
  );

  await mkdir(imageSetDirectory, { recursive: true });
  await writeFile(resolve(imageSetDirectory, outputFilename), svg);
  await writeFile(
    resolve(imageSetDirectory, "Contents.json"),
    json({
      images: [{ filename: outputFilename, idiom: "universal" }],
      info: { author: "xcode", version: 1 },
      properties: {
        "preserves-vector-representation": true,
        "template-rendering-intent": "template",
      },
    }),
  );
}

const swiftCases = iconNames
  .map((iconName) => {
    const caseName = swiftCaseName(iconName);
    return caseName === iconName
      ? `    case ${caseName}`
      : `    case ${caseName} = "${iconName}"`;
  })
  .join("\n");

await writeFile(
  generatedSwiftPath,
  `// Generated by apps/web/scripts/generate-ios-lucide-icons.ts.\n// Do not edit.\n\nextension NoemaIcon {\n  enum Name: String {\n${swiftCases}\n  }\n}\n`,
);
await mkdir(resolve(licensePath, ".."), { recursive: true });
await cp(resolve(sourceDirectory, "LICENSE"), licensePath);

console.log(`Generated ${iconNames.length} iOS Lucide icons.`);
