// Generate native form controls from the installed Astryx Button implementation.
// Run from apps/web: bun scripts/render-public-buttons.tsx
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { Button } from "@astryxdesign/core/Button";
const buttons = [
  ["deny", "secondary", "Not now"],
  ["approve", "primary", "Connect app"]
] as const;
const returnLink = renderToStaticMarkup(
  <Button as="a" href="/" variant="primary" label="Return to Noema" />
);
const html =
  buttons
    .map(([decision, variant, label]) => {
      const button = renderToStaticMarkup(
        <Button
          type="submit"
          name="decision"
          value={decision}
          variant={variant}
          label={label}
        />
      );
      return `{{define "${decision}"}}${button}{{end}}`;
    })
    .join("\n") + `\n{{define "return"}}${returnLink}{{end}}`;
await Bun.write(
  new URL("../../../internal/publicpage/buttons.html", import.meta.url),
  `<!-- Generated by apps/web/scripts/render-public-buttons.tsx. -->\n${html}\n`
);
