/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as MemoryGraphRouteImport } from './routes/memory/graph'
import { Route as SettingsToolsWebRouteImport } from './routes/settings/tools/web'
import { Route as SettingsToolsMcpsRouteImport } from './routes/settings/tools/mcps'
import { Route as SettingsSystemProvidersRouteImport } from './routes/settings/system/providers'
import { Route as SettingsSafetyUsageRouteImport } from './routes/settings/safety/usage'
import { Route as SettingsSafetyIdentitiesRouteImport } from './routes/settings/safety/identities'
import { Route as SettingsSafetyApprovalsRouteImport } from './routes/settings/safety/approvals'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoryRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const MemoryGraphRoute = MemoryGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => MemoryRoute,
} as any)
const SettingsToolsWebRoute = SettingsToolsWebRouteImport.update({
  id: '/tools/web',
  path: '/tools/web',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsMcpsRoute = SettingsToolsMcpsRouteImport.update({
  id: '/tools/mcps',
  path: '/tools/mcps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemProvidersRoute = SettingsSystemProvidersRouteImport.update({
  id: '/system/providers',
  path: '/system/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyUsageRoute = SettingsSafetyUsageRouteImport.update({
  id: '/safety/usage',
  path: '/safety/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyIdentitiesRoute =
  SettingsSafetyIdentitiesRouteImport.update({
    id: '/safety/identities',
    path: '/safety/identities',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSafetyApprovalsRoute = SettingsSafetyApprovalsRouteImport.update({
  id: '/safety/approvals',
  path: '/safety/approvals',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/memory/graph': typeof MemoryGraphRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/safety/approvals': typeof SettingsSafetyApprovalsRoute
  '/settings/safety/identities': typeof SettingsSafetyIdentitiesRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory/graph': typeof MemoryGraphRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/memory': typeof MemoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/safety/approvals': typeof SettingsSafetyApprovalsRoute
  '/settings/safety/identities': typeof SettingsSafetyIdentitiesRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/memory/graph': typeof MemoryGraphRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/safety/approvals': typeof SettingsSafetyApprovalsRoute
  '/settings/safety/identities': typeof SettingsSafetyIdentitiesRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/settings'
    | '/memory/graph'
    | '/settings/agents'
    | '/memory/'
    | '/settings/'
    | '/settings/safety/approvals'
    | '/settings/safety/identities'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memory/graph'
    | '/settings/agents'
    | '/memory'
    | '/settings'
    | '/settings/safety/approvals'
    | '/settings/safety/identities'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/settings'
    | '/memory/graph'
    | '/settings/agents'
    | '/memory/'
    | '/settings/'
    | '/settings/safety/approvals'
    | '/settings/safety/identities'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/': {
      id: '/memory/'
      path: '/'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/graph': {
      id: '/memory/graph'
      path: '/graph'
      fullPath: '/memory/graph'
      preLoaderRoute: typeof MemoryGraphRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/settings/tools/web': {
      id: '/settings/tools/web'
      path: '/tools/web'
      fullPath: '/settings/tools/web'
      preLoaderRoute: typeof SettingsToolsWebRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/mcps': {
      id: '/settings/tools/mcps'
      path: '/tools/mcps'
      fullPath: '/settings/tools/mcps'
      preLoaderRoute: typeof SettingsToolsMcpsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/providers': {
      id: '/settings/system/providers'
      path: '/system/providers'
      fullPath: '/settings/system/providers'
      preLoaderRoute: typeof SettingsSystemProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/usage': {
      id: '/settings/safety/usage'
      path: '/safety/usage'
      fullPath: '/settings/safety/usage'
      preLoaderRoute: typeof SettingsSafetyUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/identities': {
      id: '/settings/safety/identities'
      path: '/safety/identities'
      fullPath: '/settings/safety/identities'
      preLoaderRoute: typeof SettingsSafetyIdentitiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/approvals': {
      id: '/settings/safety/approvals'
      path: '/safety/approvals'
      fullPath: '/settings/safety/approvals'
      preLoaderRoute: typeof SettingsSafetyApprovalsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface MemoryRouteChildren {
  MemoryGraphRoute: typeof MemoryGraphRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemoryGraphRoute: MemoryGraphRoute,
  MemoryIndexRoute: MemoryIndexRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsSafetyApprovalsRoute: typeof SettingsSafetyApprovalsRoute
  SettingsSafetyIdentitiesRoute: typeof SettingsSafetyIdentitiesRoute
  SettingsSafetyUsageRoute: typeof SettingsSafetyUsageRoute
  SettingsSystemProvidersRoute: typeof SettingsSystemProvidersRoute
  SettingsToolsMcpsRoute: typeof SettingsToolsMcpsRoute
  SettingsToolsWebRoute: typeof SettingsToolsWebRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsSafetyApprovalsRoute: SettingsSafetyApprovalsRoute,
  SettingsSafetyIdentitiesRoute: SettingsSafetyIdentitiesRoute,
  SettingsSafetyUsageRoute: SettingsSafetyUsageRoute,
  SettingsSystemProvidersRoute: SettingsSystemProvidersRoute,
  SettingsToolsMcpsRoute: SettingsToolsMcpsRoute,
  SettingsToolsWebRoute: SettingsToolsWebRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
