/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsMemoryRouteImport } from './routes/settings/memory'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as MemorySplatRouteImport } from './routes/memory/$'
import { Route as SettingsToolsWebRouteImport } from './routes/settings/tools/web'
import { Route as SettingsToolsMcpsRouteImport } from './routes/settings/tools/mcps'
import { Route as SettingsToolsApisRouteImport } from './routes/settings/tools/apis'
import { Route as SettingsSystemProvidersRouteImport } from './routes/settings/system/providers'
import { Route as SettingsSystemNotificationsRouteImport } from './routes/settings/system/notifications'
import { Route as SettingsSystemClientsRouteImport } from './routes/settings/system/clients'
import { Route as SettingsSafetyUsageRouteImport } from './routes/settings/safety/usage'
import { Route as SettingsSafetyPrivacyRouteImport } from './routes/settings/safety/privacy'
import { Route as SettingsToolsMcpsConnectionIdRouteImport } from './routes/settings/tools/mcps_.$connectionId'
import { Route as SettingsToolsApisConnectionIdRouteImport } from './routes/settings/tools/apis_.$connectionId'
import { Route as SettingsSystemProvidersProviderAccountIdRouteImport } from './routes/settings/system/providers_.$providerAccountId'
import { Route as SettingsSystemClientsClientIdRouteImport } from './routes/settings/system/clients_.$clientId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoryRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const MemorySplatRoute = MemorySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MemoryRoute,
} as any)
const SettingsToolsWebRoute = SettingsToolsWebRouteImport.update({
  id: '/tools/web',
  path: '/tools/web',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsMcpsRoute = SettingsToolsMcpsRouteImport.update({
  id: '/tools/mcps',
  path: '/tools/mcps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsApisRoute = SettingsToolsApisRouteImport.update({
  id: '/tools/apis',
  path: '/tools/apis',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemProvidersRoute = SettingsSystemProvidersRouteImport.update({
  id: '/system/providers',
  path: '/system/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemNotificationsRoute =
  SettingsSystemNotificationsRouteImport.update({
    id: '/system/notifications',
    path: '/system/notifications',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSystemClientsRoute = SettingsSystemClientsRouteImport.update({
  id: '/system/clients',
  path: '/system/clients',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyUsageRoute = SettingsSafetyUsageRouteImport.update({
  id: '/safety/usage',
  path: '/safety/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyPrivacyRoute = SettingsSafetyPrivacyRouteImport.update({
  id: '/safety/privacy',
  path: '/safety/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsMcpsConnectionIdRoute =
  SettingsToolsMcpsConnectionIdRouteImport.update({
    id: '/tools/mcps_/$connectionId',
    path: '/tools/mcps/$connectionId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsToolsApisConnectionIdRoute =
  SettingsToolsApisConnectionIdRouteImport.update({
    id: '/tools/apis_/$connectionId',
    path: '/tools/apis/$connectionId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSystemProvidersProviderAccountIdRoute =
  SettingsSystemProvidersProviderAccountIdRouteImport.update({
    id: '/system/providers_/$providerAccountId',
    path: '/system/providers/$providerAccountId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSystemClientsClientIdRoute =
  SettingsSystemClientsClientIdRouteImport.update({
    id: '/system/clients_/$clientId',
    path: '/system/clients/$clientId',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/clients': typeof SettingsSystemClientsRoute
  '/settings/system/notifications': typeof SettingsSystemNotificationsRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/apis': typeof SettingsToolsApisRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/settings/system/clients/$clientId': typeof SettingsSystemClientsClientIdRoute
  '/settings/system/providers/$providerAccountId': typeof SettingsSystemProvidersProviderAccountIdRoute
  '/settings/tools/apis/$connectionId': typeof SettingsToolsApisConnectionIdRoute
  '/settings/tools/mcps/$connectionId': typeof SettingsToolsMcpsConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/memory': typeof MemoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/clients': typeof SettingsSystemClientsRoute
  '/settings/system/notifications': typeof SettingsSystemNotificationsRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/apis': typeof SettingsToolsApisRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/settings/system/clients/$clientId': typeof SettingsSystemClientsClientIdRoute
  '/settings/system/providers/$providerAccountId': typeof SettingsSystemProvidersProviderAccountIdRoute
  '/settings/tools/apis/$connectionId': typeof SettingsToolsApisConnectionIdRoute
  '/settings/tools/mcps/$connectionId': typeof SettingsToolsMcpsConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/clients': typeof SettingsSystemClientsRoute
  '/settings/system/notifications': typeof SettingsSystemNotificationsRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/apis': typeof SettingsToolsApisRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/settings/system/clients_/$clientId': typeof SettingsSystemClientsClientIdRoute
  '/settings/system/providers_/$providerAccountId': typeof SettingsSystemProvidersProviderAccountIdRoute
  '/settings/tools/apis_/$connectionId': typeof SettingsToolsApisConnectionIdRoute
  '/settings/tools/mcps_/$connectionId': typeof SettingsToolsMcpsConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/settings'
    | '/tasks'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/tasks/$taskId'
    | '/memory/'
    | '/settings/'
    | '/tasks/'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/clients'
    | '/settings/system/notifications'
    | '/settings/system/providers'
    | '/settings/tools/apis'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/settings/system/clients/$clientId'
    | '/settings/system/providers/$providerAccountId'
    | '/settings/tools/apis/$connectionId'
    | '/settings/tools/mcps/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/tasks/$taskId'
    | '/memory'
    | '/settings'
    | '/tasks'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/clients'
    | '/settings/system/notifications'
    | '/settings/system/providers'
    | '/settings/tools/apis'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/settings/system/clients/$clientId'
    | '/settings/system/providers/$providerAccountId'
    | '/settings/tools/apis/$connectionId'
    | '/settings/tools/mcps/$connectionId'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/settings'
    | '/tasks'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/tasks/$taskId'
    | '/memory/'
    | '/settings/'
    | '/tasks/'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/clients'
    | '/settings/system/notifications'
    | '/settings/system/providers'
    | '/settings/tools/apis'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/settings/system/clients_/$clientId'
    | '/settings/system/providers_/$providerAccountId'
    | '/settings/tools/apis_/$connectionId'
    | '/settings/tools/mcps_/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/': {
      id: '/memory/'
      path: '/'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/$': {
      id: '/memory/$'
      path: '/$'
      fullPath: '/memory/$'
      preLoaderRoute: typeof MemorySplatRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/settings/tools/web': {
      id: '/settings/tools/web'
      path: '/tools/web'
      fullPath: '/settings/tools/web'
      preLoaderRoute: typeof SettingsToolsWebRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/mcps': {
      id: '/settings/tools/mcps'
      path: '/tools/mcps'
      fullPath: '/settings/tools/mcps'
      preLoaderRoute: typeof SettingsToolsMcpsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/apis': {
      id: '/settings/tools/apis'
      path: '/tools/apis'
      fullPath: '/settings/tools/apis'
      preLoaderRoute: typeof SettingsToolsApisRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/providers': {
      id: '/settings/system/providers'
      path: '/system/providers'
      fullPath: '/settings/system/providers'
      preLoaderRoute: typeof SettingsSystemProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/notifications': {
      id: '/settings/system/notifications'
      path: '/system/notifications'
      fullPath: '/settings/system/notifications'
      preLoaderRoute: typeof SettingsSystemNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/clients': {
      id: '/settings/system/clients'
      path: '/system/clients'
      fullPath: '/settings/system/clients'
      preLoaderRoute: typeof SettingsSystemClientsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/usage': {
      id: '/settings/safety/usage'
      path: '/safety/usage'
      fullPath: '/settings/safety/usage'
      preLoaderRoute: typeof SettingsSafetyUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/privacy': {
      id: '/settings/safety/privacy'
      path: '/safety/privacy'
      fullPath: '/settings/safety/privacy'
      preLoaderRoute: typeof SettingsSafetyPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/mcps_/$connectionId': {
      id: '/settings/tools/mcps_/$connectionId'
      path: '/tools/mcps/$connectionId'
      fullPath: '/settings/tools/mcps/$connectionId'
      preLoaderRoute: typeof SettingsToolsMcpsConnectionIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/apis_/$connectionId': {
      id: '/settings/tools/apis_/$connectionId'
      path: '/tools/apis/$connectionId'
      fullPath: '/settings/tools/apis/$connectionId'
      preLoaderRoute: typeof SettingsToolsApisConnectionIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/providers_/$providerAccountId': {
      id: '/settings/system/providers_/$providerAccountId'
      path: '/system/providers/$providerAccountId'
      fullPath: '/settings/system/providers/$providerAccountId'
      preLoaderRoute: typeof SettingsSystemProvidersProviderAccountIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/clients_/$clientId': {
      id: '/settings/system/clients_/$clientId'
      path: '/system/clients/$clientId'
      fullPath: '/settings/system/clients/$clientId'
      preLoaderRoute: typeof SettingsSystemClientsClientIdRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface MemoryRouteChildren {
  MemorySplatRoute: typeof MemorySplatRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemorySplatRoute: MemorySplatRoute,
  MemoryIndexRoute: MemoryIndexRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsSafetyPrivacyRoute: typeof SettingsSafetyPrivacyRoute
  SettingsSafetyUsageRoute: typeof SettingsSafetyUsageRoute
  SettingsSystemClientsRoute: typeof SettingsSystemClientsRoute
  SettingsSystemNotificationsRoute: typeof SettingsSystemNotificationsRoute
  SettingsSystemProvidersRoute: typeof SettingsSystemProvidersRoute
  SettingsToolsApisRoute: typeof SettingsToolsApisRoute
  SettingsToolsMcpsRoute: typeof SettingsToolsMcpsRoute
  SettingsToolsWebRoute: typeof SettingsToolsWebRoute
  SettingsSystemClientsClientIdRoute: typeof SettingsSystemClientsClientIdRoute
  SettingsSystemProvidersProviderAccountIdRoute: typeof SettingsSystemProvidersProviderAccountIdRoute
  SettingsToolsApisConnectionIdRoute: typeof SettingsToolsApisConnectionIdRoute
  SettingsToolsMcpsConnectionIdRoute: typeof SettingsToolsMcpsConnectionIdRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsSafetyPrivacyRoute: SettingsSafetyPrivacyRoute,
  SettingsSafetyUsageRoute: SettingsSafetyUsageRoute,
  SettingsSystemClientsRoute: SettingsSystemClientsRoute,
  SettingsSystemNotificationsRoute: SettingsSystemNotificationsRoute,
  SettingsSystemProvidersRoute: SettingsSystemProvidersRoute,
  SettingsToolsApisRoute: SettingsToolsApisRoute,
  SettingsToolsMcpsRoute: SettingsToolsMcpsRoute,
  SettingsToolsWebRoute: SettingsToolsWebRoute,
  SettingsSystemClientsClientIdRoute: SettingsSystemClientsClientIdRoute,
  SettingsSystemProvidersProviderAccountIdRoute:
    SettingsSystemProvidersProviderAccountIdRoute,
  SettingsToolsApisConnectionIdRoute: SettingsToolsApisConnectionIdRoute,
  SettingsToolsMcpsConnectionIdRoute: SettingsToolsMcpsConnectionIdRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
