/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsMemoryRouteImport } from './routes/settings/memory'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as MemorySplatRouteImport } from './routes/memory/$'
import { Route as WorkTasksTaskIdRouteImport } from './routes/work/tasks/$taskId'
import { Route as SettingsToolsWebRouteImport } from './routes/settings/tools/web'
import { Route as SettingsToolsMcpsRouteImport } from './routes/settings/tools/mcps'
import { Route as SettingsToolsConnectionsRouteImport } from './routes/settings/tools/connections'
import { Route as SettingsSystemProvidersRouteImport } from './routes/settings/system/providers'
import { Route as SettingsSafetyUsageRouteImport } from './routes/settings/safety/usage'
import { Route as SettingsSafetyPrivacyRouteImport } from './routes/settings/safety/privacy'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoryRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const MemorySplatRoute = MemorySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MemoryRoute,
} as any)
const WorkTasksTaskIdRoute = WorkTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => WorkRoute,
} as any)
const SettingsToolsWebRoute = SettingsToolsWebRouteImport.update({
  id: '/tools/web',
  path: '/tools/web',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsMcpsRoute = SettingsToolsMcpsRouteImport.update({
  id: '/tools/mcps',
  path: '/tools/mcps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsToolsConnectionsRoute =
  SettingsToolsConnectionsRouteImport.update({
    id: '/tools/connections',
    path: '/tools/connections',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSystemProvidersRoute = SettingsSystemProvidersRouteImport.update({
  id: '/system/providers',
  path: '/system/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyUsageRoute = SettingsSafetyUsageRouteImport.update({
  id: '/safety/usage',
  path: '/safety/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSafetyPrivacyRoute = SettingsSafetyPrivacyRouteImport.update({
  id: '/safety/privacy',
  path: '/safety/privacy',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/connections': typeof SettingsToolsConnectionsRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/work/tasks/$taskId': typeof WorkTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/memory': typeof MemoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/work': typeof WorkIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/connections': typeof SettingsToolsConnectionsRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/work/tasks/$taskId': typeof WorkTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/memory/$': typeof MemorySplatRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/settings/safety/privacy': typeof SettingsSafetyPrivacyRoute
  '/settings/safety/usage': typeof SettingsSafetyUsageRoute
  '/settings/system/providers': typeof SettingsSystemProvidersRoute
  '/settings/tools/connections': typeof SettingsToolsConnectionsRoute
  '/settings/tools/mcps': typeof SettingsToolsMcpsRoute
  '/settings/tools/web': typeof SettingsToolsWebRoute
  '/work/tasks/$taskId': typeof WorkTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/settings'
    | '/work'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/memory/'
    | '/settings/'
    | '/work/'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/connections'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/work/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/memory'
    | '/settings'
    | '/work'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/connections'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/work/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/settings'
    | '/work'
    | '/memory/$'
    | '/settings/agents'
    | '/settings/memory'
    | '/settings/models'
    | '/memory/'
    | '/settings/'
    | '/work/'
    | '/settings/safety/privacy'
    | '/settings/safety/usage'
    | '/settings/system/providers'
    | '/settings/tools/connections'
    | '/settings/tools/mcps'
    | '/settings/tools/web'
    | '/work/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/': {
      id: '/memory/'
      path: '/'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/memory/$': {
      id: '/memory/$'
      path: '/$'
      fullPath: '/memory/$'
      preLoaderRoute: typeof MemorySplatRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/work/tasks/$taskId': {
      id: '/work/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/work/tasks/$taskId'
      preLoaderRoute: typeof WorkTasksTaskIdRouteImport
      parentRoute: typeof WorkRoute
    }
    '/settings/tools/web': {
      id: '/settings/tools/web'
      path: '/tools/web'
      fullPath: '/settings/tools/web'
      preLoaderRoute: typeof SettingsToolsWebRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/mcps': {
      id: '/settings/tools/mcps'
      path: '/tools/mcps'
      fullPath: '/settings/tools/mcps'
      preLoaderRoute: typeof SettingsToolsMcpsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tools/connections': {
      id: '/settings/tools/connections'
      path: '/tools/connections'
      fullPath: '/settings/tools/connections'
      preLoaderRoute: typeof SettingsToolsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system/providers': {
      id: '/settings/system/providers'
      path: '/system/providers'
      fullPath: '/settings/system/providers'
      preLoaderRoute: typeof SettingsSystemProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/usage': {
      id: '/settings/safety/usage'
      path: '/safety/usage'
      fullPath: '/settings/safety/usage'
      preLoaderRoute: typeof SettingsSafetyUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/safety/privacy': {
      id: '/settings/safety/privacy'
      path: '/safety/privacy'
      fullPath: '/settings/safety/privacy'
      preLoaderRoute: typeof SettingsSafetyPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface MemoryRouteChildren {
  MemorySplatRoute: typeof MemorySplatRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemorySplatRoute: MemorySplatRoute,
  MemoryIndexRoute: MemoryIndexRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsSafetyPrivacyRoute: typeof SettingsSafetyPrivacyRoute
  SettingsSafetyUsageRoute: typeof SettingsSafetyUsageRoute
  SettingsSystemProvidersRoute: typeof SettingsSystemProvidersRoute
  SettingsToolsConnectionsRoute: typeof SettingsToolsConnectionsRoute
  SettingsToolsMcpsRoute: typeof SettingsToolsMcpsRoute
  SettingsToolsWebRoute: typeof SettingsToolsWebRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsSafetyPrivacyRoute: SettingsSafetyPrivacyRoute,
  SettingsSafetyUsageRoute: SettingsSafetyUsageRoute,
  SettingsSystemProvidersRoute: SettingsSystemProvidersRoute,
  SettingsToolsConnectionsRoute: SettingsToolsConnectionsRoute,
  SettingsToolsMcpsRoute: SettingsToolsMcpsRoute,
  SettingsToolsWebRoute: SettingsToolsWebRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkRouteChildren {
  WorkIndexRoute: typeof WorkIndexRoute
  WorkTasksTaskIdRoute: typeof WorkTasksTaskIdRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkIndexRoute: WorkIndexRoute,
  WorkTasksTaskIdRoute: WorkTasksTaskIdRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
