//! Web frontend protocol types and TypeScript binding generation.

use std::{fs, path::Path};

use serde::{Deserialize, Serialize};
use ts_rs::{Config as TsConfig, TS};

use crate::{AgentStatus, StartedConversation, TurnTranscriptItem};

const GENERATED_HEADER: &str = "/* @generated by `cargo run --manifest-path crates/noema-core/Cargo.toml --bin export_frontend_types`. Do not edit by hand. */\n\n";

/// Local service status shown by the web UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "snake_case")]
pub enum WebLocalServiceStatus {
    /// The local Noema daemon is running.
    Running,
}

/// Assistant connection exposed to the web UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "snake_case")]
pub enum WebAssistantConnection {
    /// The daemon is using Codex app-server for chat turns.
    Codex,
}

/// Memory storage readiness shown by the web UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "snake_case")]
pub enum WebMemoryStorageStatus {
    /// The canonical SQLite database is present.
    Ready,
    /// The canonical SQLite database has not been created yet.
    Initializing,
}

/// Status returned by `GET /api/status`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "snake_case")]
pub struct WebStatus {
    local_service: WebLocalServiceStatus,
    assistant_connection: WebAssistantConnection,
    memory_storage: WebMemoryStorageStatus,
}

impl WebStatus {
    /// Build a status response for the local web UI.
    #[must_use]
    pub(crate) const fn new(memory_storage: WebMemoryStorageStatus) -> Self {
        Self {
            local_service: WebLocalServiceStatus::Running,
            assistant_connection: WebAssistantConnection::Codex,
            memory_storage,
        }
    }
}

/// Messages accepted from the web frontend over `/api/chat/ws`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
#[ts(tag = "type", rename_all = "snake_case")]
pub enum WebClientMessage {
    /// Start a new daemon-backed conversation.
    #[serde(rename = "conversation_start")]
    #[ts(rename = "conversation_start")]
    Start {
        /// Optional model override.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        model: Option<String>,
        /// Optional working directory for the conversation.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        cwd: Option<String>,
    },
    /// Send one user turn to an existing conversation.
    #[serde(rename = "conversation_turn")]
    #[ts(rename = "conversation_turn")]
    Turn {
        /// Daemon conversation id.
        conversation_id: String,
        /// User input.
        input: String,
        /// Frontend-generated id for correlating optimistic UI state.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        client_message_id: Option<String>,
    },
    /// End a conversation and release provider state.
    #[serde(rename = "conversation_end")]
    #[ts(rename = "conversation_end")]
    End {
        /// Daemon conversation id.
        conversation_id: String,
    },
}

/// Messages emitted to the web frontend over `/api/chat/ws`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
#[ts(tag = "type", rename_all = "snake_case")]
pub enum WebServerMessage {
    /// Generic success response.
    Ok {
        /// Optional success message.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        message: Option<String>,
    },
    /// Conversation start response.
    ConversationStarted {
        /// Daemon conversation id.
        conversation_id: String,
        /// Provider used for the conversation.
        provider: String,
        /// Provider-native thread id.
        provider_thread_id: String,
    },
    /// One persisted conversation item emitted by an in-progress turn.
    ConversationItem {
        /// Daemon conversation id.
        conversation_id: String,
        /// Frontend-generated id originally sent with the user message.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        client_message_id: Option<String>,
        /// Durable conversation item id.
        item_id: String,
        /// Durable conversation turn id.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        turn_id: Option<String>,
        /// Transcript item to render in chat.
        item: TurnTranscriptItem,
    },
    /// Live agent status changed for a conversation.
    AgentStatusChanged {
        /// Daemon conversation id.
        conversation_id: String,
        /// Current agent coordination status.
        status: AgentStatus,
    },
    /// Durable replay for a conversation transcript.
    ConversationReplay {
        /// Daemon conversation id.
        conversation_id: String,
        /// Persisted conversation items in replay order.
        items: Vec<WebConversationItem>,
    },
    /// Turn completion response.
    TurnCompleted {
        /// Daemon conversation id.
        conversation_id: String,
        /// Frontend-generated id originally sent with the user message.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        client_message_id: Option<String>,
    },
    /// Error response returned over the web protocol.
    Error {
        /// Human-readable error message.
        message: String,
    },
}

/// One persisted conversation item in web replay.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
pub struct WebConversationItem {
    /// Durable conversation item id.
    item_id: String,
    /// Durable conversation turn id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    turn_id: Option<String>,
    /// Transcript item to render in chat.
    item: TurnTranscriptItem,
}

impl WebServerMessage {
    pub(crate) fn conversation_started(started: StartedConversation) -> Self {
        Self::ConversationStarted {
            conversation_id: started.conversation_id,
            provider: "codex".to_string(),
            provider_thread_id: started.provider_thread_id,
        }
    }
}

/// Return the generated TypeScript binding file content.
#[must_use]
pub fn generated_frontend_typescript() -> String {
    let config = TsConfig::default();
    let declarations = [
        exported_decl::<AgentStatus>(&config),
        exported_decl::<crate::TurnActivityStatus>(&config),
        exported_decl::<TurnTranscriptItem>(&config),
        exported_decl::<WebLocalServiceStatus>(&config),
        exported_decl::<WebAssistantConnection>(&config),
        exported_decl::<WebMemoryStorageStatus>(&config),
        exported_decl::<WebStatus>(&config),
        exported_decl::<WebConversationItem>(&config),
        exported_decl::<WebClientMessage>(&config),
        exported_decl::<WebServerMessage>(&config),
    ];

    format!("{GENERATED_HEADER}{}\n", declarations.join("\n\n"))
}

/// Write generated TypeScript bindings to `path`.
///
/// # Errors
///
/// Returns an error when the output directory cannot be created or the file
/// cannot be written.
pub fn write_frontend_typescript(path: &Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, generated_frontend_typescript())
}

fn exported_decl<T: TS>(config: &TsConfig) -> String {
    format!("export {}", T::decl(config))
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_frontend_types_are_current() {
        let expected = generated_frontend_typescript();
        let actual = include_str!("../web/src/generated/noema.ts");

        assert_eq!(
            actual, expected,
            "generated frontend types are stale; run `cargo run --manifest-path crates/noema-core/Cargo.toml --bin export_frontend_types`"
        );
    }

    #[test]
    fn web_conversation_item_and_status_messages_serialize() {
        let message = WebServerMessage::ConversationItem {
            conversation_id: "conversation_1".to_string(),
            client_message_id: Some("client_1".to_string()),
            item_id: "item_1".to_string(),
            turn_id: Some("turn_1".to_string()),
            item: TurnTranscriptItem::AssistantText {
                text: "hello".to_string(),
            },
        };
        let encoded = serde_json::to_string(&message).expect("encode");
        assert!(encoded.contains(r#""type":"conversation_item""#));
        assert!(encoded.contains(r#""client_message_id":"client_1""#));
        assert!(encoded.contains(r#""item_id":"item_1""#));
        assert!(encoded.contains(r#""turn_id":"turn_1""#));
        let decoded: WebServerMessage = serde_json::from_str(&encoded).expect("decode");
        assert_eq!(decoded, message);

        let message = WebServerMessage::AgentStatusChanged {
            conversation_id: "conversation_1".to_string(),
            status: AgentStatus::Idle,
        };
        let encoded = serde_json::to_string(&message).expect("encode");
        assert!(encoded.contains(r#""type":"agent_status_changed""#));
        assert!(encoded.contains(r#""status":"idle""#));
        let decoded: WebServerMessage = serde_json::from_str(&encoded).expect("decode");
        assert_eq!(decoded, message);

        let message = WebServerMessage::ConversationReplay {
            conversation_id: "conversation_1".to_string(),
            items: vec![WebConversationItem {
                item_id: "item_1".to_string(),
                turn_id: Some("turn_1".to_string()),
                item: TurnTranscriptItem::UserText {
                    text: "hello".to_string(),
                },
            }],
        };
        let encoded = serde_json::to_string(&message).expect("encode");
        assert!(encoded.contains(r#""type":"conversation_replay""#));
        assert!(encoded.contains(r#""items":[{"#));
        let decoded: WebServerMessage = serde_json::from_str(&encoded).expect("decode");
        assert_eq!(decoded, message);
    }
}
