package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/kpsuperplane/noema/internal/graphql/model"
	"github.com/kpsuperplane/noema/internal/store"
)

// ConfigureApnsProvider is the resolver for the configureApnsProvider field.
func (r *mutationRootResolver) ConfigureApnsProvider(ctx context.Context, input model.ConfigureApnsProviderInput) (*model.ApnsProviderStatus, error) {
	return r.configureAPNS(ctx, input)
}

// RemoveApnsProvider is the resolver for the removeApnsProvider field.
func (r *mutationRootResolver) RemoveApnsProvider(ctx context.Context, expectedRevision int) (*model.ApnsProviderStatus, error) {
	return r.removeAPNS(ctx, expectedRevision)
}

// RegisterClientNotifications is the resolver for the registerClientNotifications field.
func (r *mutationRootResolver) RegisterClientNotifications(ctx context.Context, input model.RegisterClientNotificationsInput) (*model.ClientNotificationStatus, error) {
	return r.registerClientNotifications(ctx, input)
}

// DisableClientNotifications is the resolver for the disableClientNotifications field.
func (r *mutationRootResolver) DisableClientNotifications(ctx context.Context) (*model.ClientNotificationStatus, error) {
	return r.disableClientNotifications(ctx)
}

// RegisterClientLiveActivities is the resolver for the registerClientLiveActivities field.
func (r *mutationRootResolver) RegisterClientLiveActivities(ctx context.Context, input model.RegisterClientLiveActivitiesInput) (*model.ClientLiveActivityStatus, error) {
	return r.registerClientLiveActivities(ctx, input)
}

// RegisterClientLiveActivityUpdate is the resolver for the registerClientLiveActivityUpdate field.
func (r *mutationRootResolver) RegisterClientLiveActivityUpdate(ctx context.Context, input model.RegisterClientLiveActivityUpdateInput) (bool, error) {
	return r.registerClientLiveActivityUpdate(ctx, input)
}

// DismissClientLiveActivity is the resolver for the dismissClientLiveActivity field.
func (r *mutationRootResolver) DismissClientLiveActivity(ctx context.Context, activityID string) (bool, error) {
	return r.dismissClientLiveActivity(ctx, activityID)
}

// DisableClientLiveActivities is the resolver for the disableClientLiveActivities field.
func (r *mutationRootResolver) DisableClientLiveActivities(ctx context.Context) (*model.ClientLiveActivityStatus, error) {
	return r.disableClientLiveActivities(ctx)
}

// RegisterWebPushSubscription is the resolver for the registerWebPushSubscription field.
func (r *mutationRootResolver) RegisterWebPushSubscription(ctx context.Context, input model.RegisterWebPushSubscriptionInput) (*model.WebPushStatus, error) {
	return r.registerWebPushSubscription(ctx, input)
}

// RemoveWebPushSubscription is the resolver for the removeWebPushSubscription field.
func (r *mutationRootResolver) RemoveWebPushSubscription(ctx context.Context, subscriptionID string) (bool, error) {
	return r.removeWebPushSubscription(ctx, subscriptionID)
}

// RevokeClient is the resolver for the revokeClient field.
func (r *mutationRootResolver) RevokeClient(ctx context.Context, clientID string) (*model.Client, error) {
	return r.revokeClient(ctx, clientID)
}

// RevokeAllClients is the resolver for the revokeAllClients field.
func (r *mutationRootResolver) RevokeAllClients(ctx context.Context) (int, error) {
	return r.revokeAllClients(ctx)
}

// ConfirmOnboardingModelSelections is the resolver for the confirmOnboardingModelSelections field.
func (r *mutationRootResolver) ConfirmOnboardingModelSelections(ctx context.Context, input model.ConfirmOnboardingModelSelectionsInput) (*model.OnboardingStatus, error) {
	return r.confirmOnboardingModelSelections(ctx, input)
}

// AddMcpConnection is the resolver for the addMcpConnection field.
func (r *mutationRootResolver) AddMcpConnection(ctx context.Context, input model.AddMcpConnectionInput) (*model.McpServerSetupResult, error) {
	return r.addMCPConnection(ctx, input)
}

// SaveCapabilityConnectionPolicy is the resolver for the saveCapabilityConnectionPolicy field.
func (r *mutationRootResolver) SaveCapabilityConnectionPolicy(ctx context.Context, input model.SaveCapabilityConnectionPolicyInput) (*model.CapabilityConnection, error) {
	return r.saveMCPConnectionPolicy(ctx, input)
}

// SaveCapabilityConnectionLabel is the resolver for the saveCapabilityConnectionLabel field.
func (r *mutationRootResolver) SaveCapabilityConnectionLabel(ctx context.Context, input model.SaveCapabilityConnectionLabelInput) (*model.CapabilityConnection, error) {
	return r.saveMCPConnectionLabel(ctx, input)
}

// SaveCapabilityToolOverride is the resolver for the saveCapabilityToolOverride field.
func (r *mutationRootResolver) SaveCapabilityToolOverride(ctx context.Context, input model.SaveCapabilityToolOverrideInput) (*model.CapabilityManagedTool, error) {
	return r.changeMCPTool(ctx, input)
}

// ResetCapabilityToolPolicy is the resolver for the resetCapabilityToolPolicy field.
func (r *mutationRootResolver) ResetCapabilityToolPolicy(ctx context.Context, input model.ResetCapabilityToolPolicyInput) (*model.CapabilityManagedTool, error) {
	return r.changeMCPTool(ctx, input)
}

// SetCapabilityToolEnabled is the resolver for the setCapabilityToolEnabled field.
func (r *mutationRootResolver) SetCapabilityToolEnabled(ctx context.Context, input model.SetCapabilityToolEnabledInput) (*model.CapabilityManagedTool, error) {
	return r.changeMCPTool(ctx, input)
}

// ResolveGovernedAction is the resolver for the resolveGovernedAction field.
func (r *mutationRootResolver) ResolveGovernedAction(ctx context.Context, input model.ResolveGovernedActionInput) (*model.GovernedAction, error) {
	return r.resolveActionRequest(ctx, input)
}

// StartMcpAuthentication is the resolver for the startMcpAuthentication field.
func (r *mutationRootResolver) StartMcpAuthentication(ctx context.Context, input model.StartMcpAuthenticationInput) (*model.McpOAuthSetupAttempt, error) {
	return r.startMCPCallAuthentication(ctx, input)
}

// SkipMcpAuthentication is the resolver for the skipMcpAuthentication field.
func (r *mutationRootResolver) SkipMcpAuthentication(ctx context.Context, input model.SkipMcpAuthenticationInput) (*model.McpAuthenticationIntervention, error) {
	return r.skipMCPCallAuthentication(ctx, input)
}

// ResolveMcpSetupIntervention is the resolver for the resolveMcpSetupIntervention field.
func (r *mutationRootResolver) ResolveMcpSetupIntervention(ctx context.Context, input model.ResolveMcpSetupInterventionInput) (bool, error) {
	return r.resolveMCPSetupIntervention(ctx, input)
}

// StartAdapterAuthentication is the resolver for the startAdapterAuthentication field.
func (r *mutationRootResolver) StartAdapterAuthentication(ctx context.Context, input model.StartAdapterAuthenticationInput) (*model.AdapterOauthSetupAttempt, error) {
	panic(fmt.Errorf("not implemented: StartAdapterAuthentication - startAdapterAuthentication"))
}

// SkipAdapterAuthentication is the resolver for the skipAdapterAuthentication field.
func (r *mutationRootResolver) SkipAdapterAuthentication(ctx context.Context, input model.SkipAdapterAuthenticationInput) (*model.AdapterAuthenticationIntervention, error) {
	panic(fmt.Errorf("not implemented: SkipAdapterAuthentication - skipAdapterAuthentication"))
}

// InstallLocalModel is the resolver for the installLocalModel field.
func (r *mutationRootResolver) InstallLocalModel(ctx context.Context, input model.InstallLocalModelInput) (*model.LocalModelInstallation, error) {
	return nil, errLocalModelManagementUnavailable
}

// ImportLocalModel is the resolver for the importLocalModel field.
func (r *mutationRootResolver) ImportLocalModel(ctx context.Context, input model.ImportLocalModelInput) (*model.LocalModelInstallation, error) {
	return nil, errLocalModelManagementUnavailable
}

// CancelLocalModelInstall is the resolver for the cancelLocalModelInstall field.
func (r *mutationRootResolver) CancelLocalModelInstall(ctx context.Context, installationID string) (*model.LocalModelInstallation, error) {
	return nil, errLocalModelManagementUnavailable
}

// RemoveLocalModel is the resolver for the removeLocalModel field.
func (r *mutationRootResolver) RemoveLocalModel(ctx context.Context, installationID string) (bool, error) {
	return false, errLocalModelManagementUnavailable
}

// ActivateLocalModel is the resolver for the activateLocalModel field.
func (r *mutationRootResolver) ActivateLocalModel(ctx context.Context, installationID string) (*model.LocalModelInstallation, error) {
	return nil, errLocalModelManagementUnavailable
}

// SaveDefaultModelPreference is the resolver for the saveDefaultModelPreference field.
func (r *mutationRootResolver) SaveDefaultModelPreference(ctx context.Context, input model.SaveDefaultModelPreferenceInput) (*model.DefaultModelPreference, error) {
	return nil, errLocalModelManagementUnavailable
}

// RetryLocalModelRuntime is the resolver for the retryLocalModelRuntime field.
func (r *mutationRootResolver) RetryLocalModelRuntime(ctx context.Context) (model.LocalModelRuntimeStatus, error) {
	return model.LocalModelRuntimeStatusInactive, errLocalModelManagementUnavailable
}

// CreateProject is the resolver for the createProject field.
func (r *mutationRootResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.ProjectCommandPayload, error) {
	return r.createProject(ctx, input)
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationRootResolver) UpdateProject(ctx context.Context, input model.UpdateProjectInput) (*model.ProjectCommandPayload, error) {
	return r.updateProject(ctx, input)
}

// UpdateProjectDocument is the resolver for the updateProjectDocument field.
func (r *mutationRootResolver) UpdateProjectDocument(ctx context.Context, input model.UpdateProjectDocumentInput) (*model.ProjectDocumentCommandPayload, error) {
	return r.updateProjectDocument(ctx, input)
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationRootResolver) ArchiveProject(ctx context.Context, input model.ArchiveProjectInput) (*model.ProjectCommandPayload, error) {
	return r.setProjectArchived(ctx, input.ProjectID, input.ExpectedRevision, input.ClientMutationID, true)
}

// ReopenProject is the resolver for the reopenProject field.
func (r *mutationRootResolver) ReopenProject(ctx context.Context, input model.ReopenProjectInput) (*model.ProjectCommandPayload, error) {
	return r.setProjectArchived(ctx, input.ProjectID, input.ExpectedRevision, input.ClientMutationID, false)
}

// CaptureTask is the resolver for the captureTask field.
func (r *mutationRootResolver) CaptureTask(ctx context.Context, input model.CaptureTaskInput) (*model.TaskCommandPayload, error) {
	return r.captureTask(ctx, input)
}

// UpdateInboxTask is the resolver for the updateInboxTask field.
func (r *mutationRootResolver) UpdateInboxTask(ctx context.Context, input model.UpdateInboxTaskInput) (*model.TaskCommandPayload, error) {
	return r.updateInboxTask(ctx, input)
}

// QueueTask is the resolver for the queueTask field.
func (r *mutationRootResolver) QueueTask(ctx context.Context, input model.QueueTaskInput) (*model.TaskCommandPayload, error) {
	return r.queueTask(ctx, input)
}

// ScheduleTask is the resolver for the scheduleTask field.
func (r *mutationRootResolver) ScheduleTask(ctx context.Context, input model.ScheduleTaskInput) (*model.TaskCommandPayload, error) {
	return r.setTaskSchedule(ctx, input, false)
}

// RescheduleTask is the resolver for the rescheduleTask field.
func (r *mutationRootResolver) RescheduleTask(ctx context.Context, input model.ScheduleTaskInput) (*model.TaskCommandPayload, error) {
	return r.setTaskSchedule(ctx, input, true)
}

// UnscheduleTask is the resolver for the unscheduleTask field.
func (r *mutationRootResolver) UnscheduleTask(ctx context.Context, input model.UnscheduleTaskInput) (*model.TaskCommandPayload, error) {
	return r.unscheduleTask(ctx, input)
}

// RunScheduledTaskNow is the resolver for the runScheduledTaskNow field.
func (r *mutationRootResolver) RunScheduledTaskNow(ctx context.Context, input model.RunScheduledTaskNowInput) (*model.TaskCommandPayload, error) {
	return r.runScheduledTaskNow(ctx, input)
}

// UpdateTaskRecurrence is the resolver for the updateTaskRecurrence field.
func (r *mutationRootResolver) UpdateTaskRecurrence(ctx context.Context, input model.UpdateTaskRecurrenceInput) (*model.TaskCommandPayload, error) {
	return r.updateTaskRecurrence(ctx, input)
}

// PauseTaskRecurrence is the resolver for the pauseTaskRecurrence field.
func (r *mutationRootResolver) PauseTaskRecurrence(ctx context.Context, input model.TaskRecurrenceCommandInput) (*model.TaskCommandPayload, error) {
	return r.taskRecurrenceLifecycle(ctx, input, store.RecurrencePaused)
}

// ResumeTaskRecurrence is the resolver for the resumeTaskRecurrence field.
func (r *mutationRootResolver) ResumeTaskRecurrence(ctx context.Context, input model.TaskRecurrenceCommandInput) (*model.TaskCommandPayload, error) {
	return r.taskRecurrenceLifecycle(ctx, input, store.RecurrenceActive)
}

// SkipTaskRecurrenceNext is the resolver for the skipTaskRecurrenceNext field.
func (r *mutationRootResolver) SkipTaskRecurrenceNext(ctx context.Context, input model.TaskRecurrenceCommandInput) (*model.TaskCommandPayload, error) {
	return r.skipTaskRecurrenceNext(ctx, input)
}

// EndTaskRecurrence is the resolver for the endTaskRecurrence field.
func (r *mutationRootResolver) EndTaskRecurrence(ctx context.Context, input model.TaskRecurrenceCommandInput) (*model.TaskCommandPayload, error) {
	return r.taskRecurrenceLifecycle(ctx, input, store.RecurrenceEnded)
}

// RunTaskRecurrenceNow is the resolver for the runTaskRecurrenceNow field.
func (r *mutationRootResolver) RunTaskRecurrenceNow(ctx context.Context, input model.TaskRecurrenceCommandInput) (*model.TaskCommandPayload, error) {
	return r.runTaskRecurrenceNow(ctx, input)
}

// AnswerTask is the resolver for the answerTask field.
func (r *mutationRootResolver) AnswerTask(ctx context.Context, input model.AnswerTaskInput) (*model.TaskCommandPayload, error) {
	return r.answerTask(ctx, input)
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationRootResolver) RetryTask(ctx context.Context, input model.RetryTaskInput) (*model.TaskCommandPayload, error) {
	return r.retryTask(ctx, input)
}

// CancelTask is the resolver for the cancelTask field.
func (r *mutationRootResolver) CancelTask(ctx context.Context, input model.CancelTaskInput) (*model.TaskCommandPayload, error) {
	return r.cancelTask(ctx, input)
}

// ReopenTask is the resolver for the reopenTask field.
func (r *mutationRootResolver) ReopenTask(ctx context.Context, input model.ReopenTaskInput) (*model.TaskCommandPayload, error) {
	return r.reopenTask(ctx, input)
}

// UpdateTaskModelPoolEntry is the resolver for the updateTaskModelPoolEntry field.
func (r *mutationRootResolver) UpdateTaskModelPoolEntry(ctx context.Context, poolEntryID string, input model.TaskModelPoolEntryInput) (*model.TaskModelPoolEntry, error) {
	return r.updateTaskModelPoolEntry(ctx, poolEntryID, input)
}

// UpdateTaskExecutionPolicy is the resolver for the updateTaskExecutionPolicy field.
func (r *mutationRootResolver) UpdateTaskExecutionPolicy(ctx context.Context, input model.TaskExecutionPolicyInput) (*model.TaskExecutionPolicy, error) {
	panic(fmt.Errorf("not implemented: UpdateTaskExecutionPolicy - updateTaskExecutionPolicy"))
}

// StartProviderAuthAttempt is the resolver for the startProviderAuthAttempt field.
func (r *mutationRootResolver) StartProviderAuthAttempt(ctx context.Context, input model.StartProviderAuthAttemptInput) (*model.ProviderAuthAttempt, error) {
	return r.startProviderAuth(ctx, input)
}

// CancelProviderAuthAttempt is the resolver for the cancelProviderAuthAttempt field.
func (r *mutationRootResolver) CancelProviderAuthAttempt(ctx context.Context, input model.CancelProviderAuthAttemptInput) (*model.ProviderAuthAttempt, error) {
	return r.cancelProviderAuth(input.AttemptID), nil
}

// CreateProviderAccount is the resolver for the createProviderAccount field.
func (r *mutationRootResolver) CreateProviderAccount(ctx context.Context, input model.CreateProviderAccountInput) (*model.ProviderAccount, error) {
	return r.createProviderAccount(ctx, input)
}

// SaveProviderSecretInput is the resolver for the saveProviderSecretInput field.
func (r *mutationRootResolver) SaveProviderSecretInput(ctx context.Context, input model.ProviderSecretInput) (*model.ProviderAccount, error) {
	return r.saveProviderSecret(ctx, input)
}

// ClearProviderSecret is the resolver for the clearProviderSecret field.
func (r *mutationRootResolver) ClearProviderSecret(ctx context.Context, input model.ClearProviderSecretInput) (*model.ProviderAccount, error) {
	return r.clearProviderSecret(ctx, input.ProviderAccountID)
}

// DeleteProviderAccount is the resolver for the deleteProviderAccount field.
func (r *mutationRootResolver) DeleteProviderAccount(ctx context.Context, input model.DeleteProviderAccountInput) (bool, error) {
	if r.ProviderAccounts == nil {
		return false, fmt.Errorf("provider account service is unavailable")
	}
	return r.ProviderAccounts.DeleteAccount(ctx, input.ProviderAccountID)
}

// SaveAgentModelPreference is the resolver for the saveAgentModelPreference field.
func (r *mutationRootResolver) SaveAgentModelPreference(ctx context.Context, input model.SaveAgentModelPreferenceInput) (*model.AgentModelPreference, error) {
	return r.saveAgentModelPreference(ctx, input)
}

// CreateAcpAgent is the resolver for the createAcpAgent field.
func (r *mutationRootResolver) CreateAcpAgent(ctx context.Context, input model.CreateAcpAgentInput) (*model.AcpAgent, error) {
	return r.createAcpAgent(ctx, input)
}

// UpdateAcpAgent is the resolver for the updateAcpAgent field.
func (r *mutationRootResolver) UpdateAcpAgent(ctx context.Context, input model.UpdateAcpAgentInput) (*model.AcpAgent, error) {
	return r.updateAcpAgent(ctx, input)
}

// DeleteAcpAgent is the resolver for the deleteAcpAgent field.
func (r *mutationRootResolver) DeleteAcpAgent(ctx context.Context, input model.DeleteAcpAgentInput) (bool, error) {
	return r.deleteAcpAgent(ctx, input)
}

// TestAcpAgent is the resolver for the testAcpAgent field.
func (r *mutationRootResolver) TestAcpAgent(ctx context.Context, input model.TestAcpAgentInput) (*model.AcpAgent, error) {
	return r.testAcpAgent(ctx, input)
}

// AuthenticateAcpAgent is the resolver for the authenticateAcpAgent field.
func (r *mutationRootResolver) AuthenticateAcpAgent(ctx context.Context, input model.AuthenticateAcpAgentInput) (*model.AcpAgent, error) {
	return r.authenticateAcpAgent(ctx, input)
}

// SaveWebFetchSummarizerPreference is the resolver for the saveWebFetchSummarizerPreference field.
func (r *mutationRootResolver) SaveWebFetchSummarizerPreference(ctx context.Context, input model.SaveWebFetchSummarizerPreferenceInput) (*model.AgentModelPreference, error) {
	panic(fmt.Errorf("not implemented: SaveWebFetchSummarizerPreference - saveWebFetchSummarizerPreference"))
}

// SaveWebToolProviderBinding is the resolver for the saveWebToolProviderBinding field.
func (r *mutationRootResolver) SaveWebToolProviderBinding(ctx context.Context, input model.SaveWebToolProviderBindingInput) (*model.WebToolBindingSettings, error) {
	panic(fmt.Errorf("not implemented: SaveWebToolProviderBinding - saveWebToolProviderBinding"))
}

// SaveBrowserProviderRoute is the resolver for the saveBrowserProviderRoute field.
func (r *mutationRootResolver) SaveBrowserProviderRoute(ctx context.Context, input model.SaveBrowserProviderRouteInput) (*model.WebToolBindingSettings, error) {
	panic(fmt.Errorf("not implemented: SaveBrowserProviderRoute - saveBrowserProviderRoute"))
}

// SaveToolProgressAuditPreference is the resolver for the saveToolProgressAuditPreference field.
func (r *mutationRootResolver) SaveToolProgressAuditPreference(ctx context.Context, input model.SaveToolProgressAuditPreferenceInput) (*model.AgentModelPreference, error) {
	panic(fmt.Errorf("not implemented: SaveToolProgressAuditPreference - saveToolProgressAuditPreference"))
}

// SaveActionReviewerPreference is the resolver for the saveActionReviewerPreference field.
func (r *mutationRootResolver) SaveActionReviewerPreference(ctx context.Context, input model.SaveActionReviewerPreferenceInput) (*model.AgentModelPreference, error) {
	panic(fmt.Errorf("not implemented: SaveActionReviewerPreference - saveActionReviewerPreference"))
}

// UpdateMemory is the resolver for the updateMemory field.
func (r *mutationRootResolver) UpdateMemory(ctx context.Context) (*model.GraphqlNativeMemoryUpdateResult, error) {
	return r.updateMemory(ctx)
}

// SaveMemoryModelPreference is the resolver for the saveMemoryModelPreference field.
func (r *mutationRootResolver) SaveMemoryModelPreference(ctx context.Context, input model.GraphqlSaveMemoryModelPreferenceInput) (*model.AgentModelPreference, error) {
	return r.saveMemoryModelPreference(ctx, input)
}

// EnsurePrimaryConversation is the resolver for the ensurePrimaryConversation field.
func (r *mutationRootResolver) EnsurePrimaryConversation(ctx context.Context, cwd *string) (*model.PrimaryConversation, error) {
	return r.ensurePrimaryConversation(ctx, cwd)
}

// SendConversationTurn is the resolver for the sendConversationTurn field.
func (r *mutationRootResolver) SendConversationTurn(ctx context.Context, input model.SendConversationTurnInput) (*model.TurnAccepted, error) {
	return r.sendConversationTurn(ctx, input)
}

// SendMultipleChoiceSelection is the resolver for the sendMultipleChoiceSelection field.
func (r *mutationRootResolver) SendMultipleChoiceSelection(ctx context.Context, input model.SendMultipleChoiceSelectionInput) (*model.TurnAccepted, error) {
	panic(fmt.Errorf("not implemented: SendMultipleChoiceSelection - sendMultipleChoiceSelection"))
}

// SendA2UIAction is the resolver for the sendA2UIAction field.
func (r *mutationRootResolver) SendA2UIAction(ctx context.Context, input model.ProviderInteractionActionInput) (*model.TurnAccepted, error) {
	panic(fmt.Errorf("not implemented: SendA2UIAction - sendA2UIAction"))
}

// CreateConversationExternalArtifact is the resolver for the createConversationExternalArtifact field.
func (r *mutationRootResolver) CreateConversationExternalArtifact(ctx context.Context, input model.CreateConversationExternalArtifactInput) (*model.Artifact, error) {
	return r.createConversationExternalArtifact(ctx, input)
}

// CreateTaskLocalArtifact is the resolver for the createTaskLocalArtifact field.
func (r *mutationRootResolver) CreateTaskLocalArtifact(ctx context.Context, input model.CreateTaskLocalArtifactInput) (*model.Artifact, error) {
	return r.createTaskLocalArtifact(ctx, input)
}

// ApproveAdapterDefinition is the resolver for the approveAdapterDefinition field.
func (r *mutationRootResolver) ApproveAdapterDefinition(ctx context.Context, input model.ApproveAdapterDefinitionInput) (*model.AdapterDefinition, error) {
	panic(fmt.Errorf("not implemented: ApproveAdapterDefinition - approveAdapterDefinition"))
}

// CancelAdapterDefinition is the resolver for the cancelAdapterDefinition field.
func (r *mutationRootResolver) CancelAdapterDefinition(ctx context.Context, input model.CancelAdapterDefinitionInput) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelAdapterDefinition - cancelAdapterDefinition"))
}

// SetupAdapterConnection is the resolver for the setupAdapterConnection field.
func (r *mutationRootResolver) SetupAdapterConnection(ctx context.Context, input model.SetupAdapterConnectionInput) (*model.AdapterDefinition, error) {
	panic(fmt.Errorf("not implemented: SetupAdapterConnection - setupAdapterConnection"))
}

// DeleteAdapterConnection is the resolver for the deleteAdapterConnection field.
func (r *mutationRootResolver) DeleteAdapterConnection(ctx context.Context, input model.DeleteAdapterConnectionInput) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAdapterConnection - deleteAdapterConnection"))
}

// DeleteAdapterService is the resolver for the deleteAdapterService field.
func (r *mutationRootResolver) DeleteAdapterService(ctx context.Context, input model.DeleteAdapterServiceInput) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAdapterService - deleteAdapterService"))
}

// StartAdapterOauthSetup is the resolver for the startAdapterOauthSetup field.
func (r *mutationRootResolver) StartAdapterOauthSetup(ctx context.Context, input model.StartAdapterOauthSetupInput) (*model.AdapterOauthSetupAttempt, error) {
	panic(fmt.Errorf("not implemented: StartAdapterOauthSetup - startAdapterOauthSetup"))
}

// ImportAdapterOauthApplication is the resolver for the importAdapterOauthApplication field.
func (r *mutationRootResolver) ImportAdapterOauthApplication(ctx context.Context, input model.ImportAdapterOauthApplicationInput) (*model.AdapterOauthApplication, error) {
	panic(fmt.Errorf("not implemented: ImportAdapterOauthApplication - importAdapterOauthApplication"))
}

// ReplaceAdapterOauthApplication is the resolver for the replaceAdapterOauthApplication field.
func (r *mutationRootResolver) ReplaceAdapterOauthApplication(ctx context.Context, input model.ReplaceAdapterOauthApplicationInput) (*model.AdapterOauthApplication, error) {
	panic(fmt.Errorf("not implemented: ReplaceAdapterOauthApplication - replaceAdapterOauthApplication"))
}

// AttachAdapterOauthConnection is the resolver for the attachAdapterOauthConnection field.
func (r *mutationRootResolver) AttachAdapterOauthConnection(ctx context.Context, input model.AttachAdapterOauthConnectionInput) (*model.AdapterDefinition, error) {
	panic(fmt.Errorf("not implemented: AttachAdapterOauthConnection - attachAdapterOauthConnection"))
}

// DisconnectAdapterOauthGrant is the resolver for the disconnectAdapterOauthGrant field.
func (r *mutationRootResolver) DisconnectAdapterOauthGrant(ctx context.Context, input model.DisconnectAdapterOauthGrantInput) (*model.AdapterAuthorizationGrant, error) {
	panic(fmt.Errorf("not implemented: DisconnectAdapterOauthGrant - disconnectAdapterOauthGrant"))
}

// SaveAdapterOauthGrantLabel is the resolver for the saveAdapterOauthGrantLabel field.
func (r *mutationRootResolver) SaveAdapterOauthGrantLabel(ctx context.Context, input model.SaveAdapterOauthGrantLabelInput) (*model.AdapterAuthorizationGrant, error) {
	panic(fmt.Errorf("not implemented: SaveAdapterOauthGrantLabel - saveAdapterOauthGrantLabel"))
}

// DeleteAdapterOauthApplication is the resolver for the deleteAdapterOauthApplication field.
func (r *mutationRootResolver) DeleteAdapterOauthApplication(ctx context.Context, input model.DeleteAdapterOauthApplicationInput) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAdapterOauthApplication - deleteAdapterOauthApplication"))
}

// SetAdapterConnectionActive is the resolver for the setAdapterConnectionActive field.
func (r *mutationRootResolver) SetAdapterConnectionActive(ctx context.Context, input model.SetAdapterConnectionActiveInput) (*model.AdapterDefinition, error) {
	panic(fmt.Errorf("not implemented: SetAdapterConnectionActive - setAdapterConnectionActive"))
}

// CreateMcpServer is the resolver for the createMcpServer field.
func (r *mutationRootResolver) CreateMcpServer(ctx context.Context, input model.CreateMcpServerInput) (*model.McpServerSetupResult, error) {
	return r.createMCPServer(ctx, input)
}

// StartMcpServerOauthSetup is the resolver for the startMcpServerOauthSetup field.
func (r *mutationRootResolver) StartMcpServerOauthSetup(ctx context.Context, input model.StartMcpServerOAuthSetupInput) (*model.McpOAuthSetupAttempt, error) {
	return r.startMCPCreateOAuth(ctx, input)
}

// StartMcpServerReauthenticationOauthSetup is the resolver for the startMcpServerReauthenticationOauthSetup field.
func (r *mutationRootResolver) StartMcpServerReauthenticationOauthSetup(ctx context.Context, input model.StartMcpServerReauthenticationOAuthSetupInput) (*model.McpOAuthSetupAttempt, error) {
	return r.startMCPReauthOAuth(ctx, input)
}

// ContinueMcpServerSetup is the resolver for the continueMcpServerSetup field.
func (r *mutationRootResolver) ContinueMcpServerSetup(ctx context.Context, input model.ContinueMcpServerSetupInput) (*model.McpServerSetupResult, error) {
	return r.continueMCP(ctx, input)
}

// DeleteMcpServer is the resolver for the deleteMcpServer field.
func (r *mutationRootResolver) DeleteMcpServer(ctx context.Context, mcpServerID string) (bool, error) {
	return r.deleteMCP(ctx, mcpServerID)
}

// ApnsProviderStatus is the resolver for the apnsProviderStatus field.
func (r *queryRootResolver) ApnsProviderStatus(ctx context.Context) (*model.ApnsProviderStatus, error) {
	return r.apnsProviderStatus(ctx)
}

// ClientNotificationStatus is the resolver for the clientNotificationStatus field.
func (r *queryRootResolver) ClientNotificationStatus(ctx context.Context) (*model.ClientNotificationStatus, error) {
	return r.clientNotificationStatus(ctx)
}

// ClientLiveActivityStatus is the resolver for the clientLiveActivityStatus field.
func (r *queryRootResolver) ClientLiveActivityStatus(ctx context.Context) (*model.ClientLiveActivityStatus, error) {
	return r.clientLiveActivityStatus(ctx)
}

// WebPushStatus is the resolver for the webPushStatus field.
func (r *queryRootResolver) WebPushStatus(ctx context.Context, endpoint *string) (*model.WebPushStatus, error) {
	return r.webPushStatus(ctx, endpoint)
}

// Clients is the resolver for the clients field.
func (r *queryRootResolver) Clients(ctx context.Context) ([]*model.Client, error) {
	return r.clients(ctx)
}

// CapabilityIntegrations is the resolver for the capabilityIntegrations field.
func (r *queryRootResolver) CapabilityIntegrations(ctx context.Context, kind model.CapabilityIntegrationKind) ([]*model.CapabilityIntegration, error) {
	if kind == model.CapabilityIntegrationKindMcp {
		return r.mcpIntegrations(ctx)
	}
	return nil, fmt.Errorf("capability integration is unavailable")
}

// CapabilityConnection is the resolver for the capabilityConnection field.
func (r *queryRootResolver) CapabilityConnection(ctx context.Context, ref model.CapabilityConnectionRefInput) (*model.CapabilityConnection, error) {
	return r.mcpConnection(ctx, ref)
}

// CapabilityTools is the resolver for the capabilityTools field.
func (r *queryRootResolver) CapabilityTools(ctx context.Context, ref model.CapabilityConnectionRefInput) ([]*model.CapabilityManagedTool, error) {
	return r.mcpTools(ctx, ref)
}

// LocalStatus is the resolver for the localStatus field.
func (r *queryRootResolver) LocalStatus(ctx context.Context) (*model.LocalStatus, error) {
	return r.localStatus(ctx)
}

// LocalModelSetup is the resolver for the localModelSetup field.
func (r *queryRootResolver) LocalModelSetup(ctx context.Context) (*model.LocalModelSetup, error) {
	return localModelSetup(ctx)
}

// LocalModelCatalog is the resolver for the localModelCatalog field.
func (r *queryRootResolver) LocalModelCatalog(ctx context.Context) ([]*model.LocalModelCatalogEntry, error) {
	return localModelCatalog(ctx)
}

// LocalModelInstallations is the resolver for the localModelInstallations field.
func (r *queryRootResolver) LocalModelInstallations(ctx context.Context) ([]*model.LocalModelInstallation, error) {
	return []*model.LocalModelInstallation{}, nil
}

// DefaultModelPreference is the resolver for the defaultModelPreference field.
func (r *queryRootResolver) DefaultModelPreference(ctx context.Context) (*model.DefaultModelPreference, error) {
	return nil, nil
}

// OnboardingStatus is the resolver for the onboardingStatus field.
func (r *queryRootResolver) OnboardingStatus(ctx context.Context) (*model.OnboardingStatus, error) {
	return r.onboardingStatus(ctx)
}

// OnboardingModelSetup is the resolver for the onboardingModelSetup field.
func (r *queryRootResolver) OnboardingModelSetup(ctx context.Context, providerAccountID string) (*model.OnboardingModelSetup, error) {
	return r.onboardingModelSetup(ctx, providerAccountID)
}

// ProviderAuthAttempt is the resolver for the providerAuthAttempt field.
func (r *queryRootResolver) ProviderAuthAttempt(ctx context.Context, attemptID string) (*model.ProviderAuthAttempt, error) {
	return r.providerAuthAttempt(attemptID), nil
}

// ProviderAccounts is the resolver for the providerAccounts field.
func (r *queryRootResolver) ProviderAccounts(ctx context.Context) ([]*model.ProviderAccount, error) {
	return r.providerAccounts(ctx)
}

// ProviderAccountCatalog is the resolver for the providerAccountCatalog field.
func (r *queryRootResolver) ProviderAccountCatalog(ctx context.Context) ([]*model.ProviderAccountCatalogEntry, error) {
	return providerAccountCatalog(), nil
}

// Agents is the resolver for the agents field.
func (r *queryRootResolver) Agents(ctx context.Context) ([]*model.Agent, error) {
	return r.agents(ctx)
}

// AcpAgents is the resolver for the acpAgents field.
func (r *queryRootResolver) AcpAgents(ctx context.Context) ([]*model.AcpAgent, error) {
	return r.acpAgents(ctx)
}

// Task is the resolver for the task field.
func (r *queryRootResolver) Task(ctx context.Context, taskID string) (*model.TaskDetail, error) {
	return r.task(ctx, taskID)
}

// TaskWorkspaceFile is the resolver for the taskWorkspaceFile field.
func (r *queryRootResolver) TaskWorkspaceFile(ctx context.Context, taskID string, path string) (*model.TaskWorkspaceFileText, error) {
	return r.taskWorkspaceFile(ctx, taskID, path)
}

// TaskSchedulePreview is the resolver for the taskSchedulePreview field.
func (r *queryRootResolver) TaskSchedulePreview(ctx context.Context, input model.TaskSchedulePreviewInput) (*model.TaskSchedulePreview, error) {
	return r.taskSchedulePreview(input)
}

// TaskRecurrence is the resolver for the taskRecurrence field.
func (r *queryRootResolver) TaskRecurrence(ctx context.Context, recurrenceID string, first *int) (*model.TaskRecurrence, error) {
	return r.taskRecurrence(ctx, recurrenceID, first)
}

// TaskRecurrences is the resolver for the taskRecurrences field.
func (r *queryRootResolver) TaskRecurrences(ctx context.Context, workspaceID string, projectID *string, first *int) ([]*model.TaskRecurrenceSummary, error) {
	return r.taskRecurrences(ctx, workspaceID, projectID, first)
}

// Projects is the resolver for the projects field.
func (r *queryRootResolver) Projects(ctx context.Context, workspaceID string, includeArchived *bool, first *int, after *string) (*model.ProjectConnection, error) {
	return r.projects(ctx, workspaceID, includeArchived, first, after)
}

// ProjectDocument is the resolver for the projectDocument field.
func (r *queryRootResolver) ProjectDocument(ctx context.Context, projectID string) (*model.ProjectDocument, error) {
	return r.projectDocument(ctx, projectID)
}

// TasksOverview is the resolver for the tasksOverview field.
func (r *queryRootResolver) TasksOverview(ctx context.Context, workspaceID string, projectID *string) (*model.TasksOverview, error) {
	return r.tasksOverview(ctx, workspaceID, projectID)
}

// Tasks is the resolver for the tasks field.
func (r *queryRootResolver) Tasks(ctx context.Context, input model.TaskListInput, first *int, after *string) (*model.TaskConnection, error) {
	return r.tasks(ctx, input, first, after)
}

// NeedsYou is the resolver for the needsYou field.
func (r *queryRootResolver) NeedsYou(ctx context.Context, workspaceID string, projectID *string, first *int, after *string) (*model.TaskAttentionConnection, error) {
	return r.needsYou(ctx, workspaceID, projectID, first, after)
}

// PendingGovernedActions is the resolver for the pendingGovernedActions field.
func (r *queryRootResolver) PendingGovernedActions(ctx context.Context, conversationID *string, taskID *string, first *int) ([]*model.GovernedAction, error) {
	return r.pendingActionRequests(ctx, conversationID, taskID, first)
}

// PendingHumanInterventions is the resolver for the pendingHumanInterventions field.
func (r *queryRootResolver) PendingHumanInterventions(ctx context.Context, conversationID *string, taskID *string, projectID *string, first *int) ([]model.HumanIntervention, error) {
	return r.pendingHumanInterventions(ctx, conversationID, taskID, projectID, first)
}

// TaskHistory is the resolver for the taskHistory field.
func (r *queryRootResolver) TaskHistory(ctx context.Context, workspaceID string, projectID *string, kind *model.TerminalTaskKind, first *int, after *string) (*model.TaskConnection, error) {
	return r.taskHistory(ctx, workspaceID, projectID, kind, first, after)
}

// TaskRunItems is the resolver for the taskRunItems field.
func (r *queryRootResolver) TaskRunItems(ctx context.Context, runID string, first *int, after *string) (*model.TaskRunItemConnection, error) {
	return r.taskRunItems(ctx, runID, first, after)
}

// RuntimeDebugProfile is the resolver for the runtimeDebugProfile field.
func (r *queryRootResolver) RuntimeDebugProfile(ctx context.Context, input model.RuntimeDebugProfileInput) (*model.RuntimeDebugProfile, error) {
	panic(fmt.Errorf("not implemented: RuntimeDebugProfile - runtimeDebugProfile"))
}

// TaskModelPools is the resolver for the taskModelPools field.
func (r *queryRootResolver) TaskModelPools(ctx context.Context, complexity *model.TaskComplexity) ([]*model.TaskModelPoolEntry, error) {
	return r.taskModelPools(ctx, complexity)
}

// TaskExecutionPolicy is the resolver for the taskExecutionPolicy field.
func (r *queryRootResolver) TaskExecutionPolicy(ctx context.Context) (*model.TaskExecutionPolicy, error) {
	panic(fmt.Errorf("not implemented: TaskExecutionPolicy - taskExecutionPolicy"))
}

// WebFetchSettings is the resolver for the webFetchSettings field.
func (r *queryRootResolver) WebFetchSettings(ctx context.Context) (*model.WebFetchSettings, error) {
	panic(fmt.Errorf("not implemented: WebFetchSettings - webFetchSettings"))
}

// WebToolSettings is the resolver for the webToolSettings field.
func (r *queryRootResolver) WebToolSettings(ctx context.Context) (*model.WebToolSettings, error) {
	panic(fmt.Errorf("not implemented: WebToolSettings - webToolSettings"))
}

// UsageSettings is the resolver for the usageSettings field.
func (r *queryRootResolver) UsageSettings(ctx context.Context) (*model.UsageSettings, error) {
	panic(fmt.Errorf("not implemented: UsageSettings - usageSettings"))
}

// PrivacySettings is the resolver for the privacySettings field.
func (r *queryRootResolver) PrivacySettings(ctx context.Context) (*model.PrivacySettings, error) {
	panic(fmt.Errorf("not implemented: PrivacySettings - privacySettings"))
}

// McpServers is the resolver for the mcpServers field.
func (r *queryRootResolver) McpServers(ctx context.Context) ([]*model.McpServer, error) {
	return r.mcpServers(ctx)
}

// AdapterDefinitions is the resolver for the adapterDefinitions field.
func (r *queryRootResolver) AdapterDefinitions(ctx context.Context) ([]*model.AdapterDefinition, error) {
	panic(fmt.Errorf("not implemented: AdapterDefinitions - adapterDefinitions"))
}

// AdapterOauthState is the resolver for the adapterOauthState field.
func (r *queryRootResolver) AdapterOauthState(ctx context.Context) (*model.AdapterOauthState, error) {
	panic(fmt.Errorf("not implemented: AdapterOauthState - adapterOauthState"))
}

// AdapterManagement is the resolver for the adapterManagement field.
func (r *queryRootResolver) AdapterManagement(ctx context.Context) (*model.AdapterManagement, error) {
	panic(fmt.Errorf("not implemented: AdapterManagement - adapterManagement"))
}

// AdapterOauthAttempt is the resolver for the adapterOauthAttempt field.
func (r *queryRootResolver) AdapterOauthAttempt(ctx context.Context, attemptID string) (*model.AdapterOauthAttemptEvent, error) {
	panic(fmt.Errorf("not implemented: AdapterOauthAttempt - adapterOauthAttempt"))
}

// McpOauthSetupAttempt is the resolver for the mcpOauthSetupAttempt field.
func (r *queryRootResolver) McpOauthSetupAttempt(ctx context.Context, attemptID string) (*model.McpOAuthSetupAttempt, error) {
	return r.mcpAttempt(ctx, attemptID)
}

// MemorySettings is the resolver for the memorySettings field.
func (r *queryRootResolver) MemorySettings(ctx context.Context) (*model.GraphqlNativeMemorySettings, error) {
	return r.memorySettings(ctx)
}

// MemoryTree is the resolver for the memoryTree field.
func (r *queryRootResolver) MemoryTree(ctx context.Context) (*model.GraphqlNativeMemoryTree, error) {
	return r.memoryTree(ctx)
}

// MemoryPage is the resolver for the memoryPage field.
func (r *queryRootResolver) MemoryPage(ctx context.Context, pageID string) (*model.GraphqlNativeMemoryPage, error) {
	return r.memoryPage(ctx, pageID)
}

// PrimaryConversation is the resolver for the primaryConversation field.
func (r *queryRootResolver) PrimaryConversation(ctx context.Context) (*model.PrimaryConversation, error) {
	return r.primaryConversation(ctx)
}

// ConversationTranscriptPage is the resolver for the conversationTranscriptPage field.
func (r *queryRootResolver) ConversationTranscriptPage(ctx context.Context, input model.ConversationTranscriptPageInput) (*model.ConversationTranscriptPage, error) {
	return r.conversationTranscriptPage(ctx, input)
}

// Artifacts is the resolver for the artifacts field.
func (r *queryRootResolver) Artifacts(ctx context.Context, ownerObjectType string, ownerObjectID string, limit *int) ([]*model.Artifact, error) {
	return r.artifacts(ctx, ownerObjectType, ownerObjectID, limit)
}

// ArtifactVersionDetail is the resolver for the artifactVersionDetail field.
func (r *queryRootResolver) ArtifactVersionDetail(ctx context.Context, artifactVersionID string) (*model.ArtifactVersionDetail, error) {
	return r.artifactVersionDetail(ctx, artifactVersionID)
}

// AdapterOauthAttemptEvents is the resolver for the adapterOauthAttemptEvents field.
func (r *subscriptionRootResolver) AdapterOauthAttemptEvents(ctx context.Context, attemptID string) (<-chan *model.AdapterOauthAttemptEvent, error) {
	panic(fmt.Errorf("not implemented: AdapterOauthAttemptEvents - adapterOauthAttemptEvents"))
}

// ClientNotificationPresence is the resolver for the clientNotificationPresence field.
func (r *subscriptionRootResolver) ClientNotificationPresence(ctx context.Context) (<-chan *model.ClientNotificationPresenceEvent, error) {
	return r.clientNotificationPresence(ctx)
}

// WebPushPresence is the resolver for the webPushPresence field.
func (r *subscriptionRootResolver) WebPushPresence(ctx context.Context, subscriptionID string) (<-chan *model.WebPushPresenceEvent, error) {
	return r.webPushPresence(ctx, subscriptionID)
}

// ProviderAuthAttemptEvents is the resolver for the providerAuthAttemptEvents field.
func (r *subscriptionRootResolver) ProviderAuthAttemptEvents(ctx context.Context, attemptID string) (<-chan *model.ProviderAuthAttempt, error) {
	return r.providerAuthEvents(ctx, attemptID)
}

// LocalModelEvents is the resolver for the localModelEvents field.
func (r *subscriptionRootResolver) LocalModelEvents(ctx context.Context, after *string) (<-chan *model.LocalModelEvent, error) {
	return localModelEvents(ctx), nil
}

// ConversationEvents is the resolver for the conversationEvents field.
func (r *subscriptionRootResolver) ConversationEvents(ctx context.Context, conversationID string) (<-chan model.ConversationEvent, error) {
	return r.conversationEvents(ctx, conversationID)
}

// MemoryEvents is the resolver for the memoryEvents field.
func (r *subscriptionRootResolver) MemoryEvents(ctx context.Context) (<-chan *model.GraphqlNativeMemoryTree, error) {
	return r.memoryEvents(ctx)
}

// TasksEvents is the resolver for the tasksEvents field.
func (r *subscriptionRootResolver) TasksEvents(ctx context.Context, workspaceID string, after *string) (<-chan *model.TasksEvent, error) {
	return r.tasksEvents(ctx, workspaceID, after)
}

// TaskEvents is the resolver for the taskEvents field.
func (r *subscriptionRootResolver) TaskEvents(ctx context.Context, taskID string, after *string) (<-chan *model.TasksEvent, error) {
	return r.taskEvents(ctx, taskID, after)
}

// TaskRuntimeEvents is the resolver for the taskRuntimeEvents field.
func (r *subscriptionRootResolver) TaskRuntimeEvents(ctx context.Context, taskID string) (<-chan *model.GraphqlTaskRuntimeEvent, error) {
	panic(fmt.Errorf("not implemented: TaskRuntimeEvents - taskRuntimeEvents"))
}

// MutationRoot returns MutationRootResolver implementation.
func (r *Resolver) MutationRoot() MutationRootResolver { return &mutationRootResolver{r} }

// QueryRoot returns QueryRootResolver implementation.
func (r *Resolver) QueryRoot() QueryRootResolver { return &queryRootResolver{r} }

// SubscriptionRoot returns SubscriptionRootResolver implementation.
func (r *Resolver) SubscriptionRoot() SubscriptionRootResolver { return &subscriptionRootResolver{r} }

type (
	mutationRootResolver     struct{ *Resolver }
	queryRootResolver        struct{ *Resolver }
	subscriptionRootResolver struct{ *Resolver }
)
