import * as stylex from "@stylexjs/stylex";

const wikiSerif = "Georgia, 'Times New Roman', serif";
const wikiSans = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

export const styles = stylex.create({
  surface: { display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0, height: "100%", overflow: "hidden", backgroundColor: "var(--surface-base)" },
  toolbar: { display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "var(--spacing-3)", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "var(--border-subtle)", padding: "var(--spacing-3) var(--spacing-4)", fontFamily: wikiSans },
  toolbarTitle: { display: "grid", gap: "var(--spacing-0-5)", minWidth: 0, color: "var(--foreground)", fontSize: 14 },
  toolbarPath: { color: "var(--muted-foreground)", fontFamily: "var(--font-mono)", fontSize: 10, overflowWrap: "anywhere" },
  toolbarActions: { display: "flex", alignItems: "center", justifyContent: "end", flexWrap: "wrap", gap: "var(--spacing-2)" },
  status: { color: "var(--muted-foreground)", fontSize: 12 },
  updatedAt: { color: "var(--muted-foreground)", fontSize: 11 },
  notice: { flexShrink: 0, margin: "var(--spacing-3) var(--spacing-4) 0", borderRadius: 4, backgroundColor: "var(--surface-sunken)", padding: "var(--spacing-2) var(--spacing-3)", color: "var(--muted-foreground)", fontFamily: wikiSans, fontSize: 13, lineHeight: 1.45 },
  errorNotice: { backgroundColor: "color-mix(in srgb, var(--destructive) 8%, var(--surface-base))", color: "var(--destructive)" },
  layout: { display: "grid", gridTemplateColumns: "minmax(180px, 220px) minmax(0, 1fr)", flex: 1, minHeight: 0, overflow: "hidden", "@media (max-width: 760px)": { gridTemplateColumns: "1fr", gridTemplateRows: "auto 1fr" } },
  tree: { minWidth: 0, overflowY: "auto", borderRightWidth: 1, borderRightStyle: "solid", borderRightColor: "var(--border-subtle)", padding: "var(--spacing-4)", fontFamily: wikiSans, "@media (max-width: 760px)": { borderRightStyle: "none", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "var(--border-subtle)", maxHeight: 200 } },
  treeLabel: { marginBottom: "var(--spacing-2)", color: "var(--muted-foreground)", fontSize: 11, fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase" },
  children: { display: "grid", gap: "var(--spacing-1)", marginTop: "var(--spacing-1)", paddingLeft: "var(--spacing-3)" },
  pageButton: { display: "grid", gap: "var(--spacing-0-5)", width: "100%", minWidth: 0, borderWidth: 1, borderStyle: "solid", borderColor: "transparent", borderRadius: 2, backgroundColor: "transparent", padding: "var(--spacing-2)", color: "var(--foreground)", textAlign: "start", cursor: "pointer", ":hover": { backgroundColor: "var(--surface-hover)" } },
  selectedPageButton: { borderColor: "var(--border-subtle)", backgroundColor: "var(--surface-raised)" },
  pageTitle: { fontFamily: wikiSerif, fontSize: 14, fontWeight: 600, overflowWrap: "anywhere" },
  pagePath: { color: "var(--muted-foreground)", fontFamily: "var(--font-mono)", fontSize: 10, overflowWrap: "anywhere" },
  emptyTree: { margin: "var(--spacing-3) 0 0", color: "var(--muted-foreground)", fontSize: 12, lineHeight: 1.45 },
  articleScroller: { minWidth: 0, minHeight: 0, overflowY: "auto", backgroundColor: "var(--surface-base)" },
  article: { boxSizing: "border-box", width: "100%", maxWidth: 1020, minWidth: 0, margin: "0 auto", padding: "var(--spacing-6)", color: "var(--foreground)", "::after": { content: "''", display: "block", clear: "both" }, "@media (max-width: 760px)": { padding: "var(--spacing-4)" } },
  articleTitle: { margin: 0, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "var(--border-default)", paddingBottom: "var(--spacing-1-5)", color: "var(--foreground)", fontFamily: wikiSerif, fontSize: 36, fontWeight: 400, lineHeight: 1.18, overflowWrap: "anywhere", "@media (max-width: 760px)": { fontSize: 30 } },
  articleSubtitle: { marginTop: "var(--spacing-1-5)", color: "var(--muted-foreground)", fontFamily: wikiSans, fontSize: 12, overflowWrap: "anywhere" },
  contentsBox: { float: "left", width: 220, margin: "var(--spacing-4) var(--spacing-4) var(--spacing-3) 0", borderWidth: 1, borderStyle: "solid", borderColor: "var(--border-subtle)", backgroundColor: "var(--surface-sunken)", padding: "var(--spacing-3)", fontFamily: wikiSans, fontSize: 13, lineHeight: 1.6, "@media (max-width: 760px)": { float: "none", width: "auto", margin: "var(--spacing-4) 0" } },
  contentsTitle: { display: "block", marginBottom: "var(--spacing-1-5)", textAlign: "center" },
  contentsList: { display: "grid", gap: "var(--spacing-1)", margin: 0, paddingLeft: "var(--spacing-4)" },
  nestedContentsItem: { marginLeft: "var(--spacing-3)" },
  articleLink: { color: "var(--text-accent)", textDecoration: "none", ":hover": { textDecoration: "underline" } },
  articleBody: { color: "var(--foreground)", fontFamily: wikiSerif, fontSize: 15, lineHeight: 1.65 },
  articleParagraph: { margin: "var(--spacing-4) 0 0", color: "var(--foreground)", fontFamily: wikiSerif, fontSize: 15, lineHeight: 1.65, overflowWrap: "anywhere" },
  articleHeading: { clear: "both", color: "var(--foreground)", fontFamily: wikiSerif, fontWeight: 400, overflowWrap: "anywhere", scrollMarginTop: "var(--spacing-4)" },
  articleHeadingMajor: { margin: "var(--spacing-6) 0 var(--spacing-2)", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "var(--border-default)", paddingBottom: "var(--spacing-1)", fontSize: 24, lineHeight: 1.25 },
  articleHeadingMinor: { margin: "var(--spacing-4) 0 var(--spacing-2)", fontSize: 19, lineHeight: 1.3 },
  referencesSection: { clear: "both", paddingTop: "var(--spacing-1)" },
  referenceList: { display: "grid", gap: "var(--spacing-2)", margin: 0, padding: 0, color: "var(--muted-foreground)", fontFamily: wikiSans, fontSize: 12, lineHeight: 1.5, listStyle: "none" },
  referenceItem: { display: "grid", gridTemplateColumns: "24px minmax(0, 1fr)", gap: "var(--spacing-1-5)" },
  referenceNumber: { textAlign: "right", fontVariantNumeric: "tabular-nums" },
  referenceCode: { color: "var(--foreground)", fontFamily: "var(--font-mono)", fontSize: 11, overflowWrap: "anywhere" },
  stub: { marginTop: "var(--spacing-4)", borderLeftWidth: 4, borderLeftStyle: "solid", borderLeftColor: "var(--border-default)", backgroundColor: "var(--surface-sunken)", padding: "var(--spacing-2) var(--spacing-3)", color: "var(--muted-foreground)", fontFamily: wikiSans, fontSize: 13 },
  articleState: { margin: "var(--spacing-6)", color: "var(--muted-foreground)", fontFamily: wikiSans, fontSize: 13 }
});
